### ISSUE TITLE
Fails to install on FreeBSD

### ISSUE THREAD

**Issue by pprocacci** [lizmat/P5getpwnam#1]
===> Testing: P5getpwnam:ver<0.0.6>:auth<cpan:ELIZABETH>

\# Failed test 'did we see ourselves'
\# at t/getpwnam.t line 34
\# Failed test 'did we get the same number of entries the 2nd time'
\# at t/getpwnam.t line 38
\# expected: '0'
\#      got: '-27'
\# Looks like you failed 2 tests of 20
===> Testing [FAIL]: P5getpwnam:ver<0.0.6>:auth<cpan:ELIZABETH>
Aborting due to test failure: P5getpwnam:ver<0.0.6>:auth<cpan:ELIZABETH> (use --force-test to override)

% perl6 --version
This is Rakudo Star version 2019.03.1 built on MoarVM version 2019.03
implementing Perl 6.d.

**Comment by lizmat** [comment]
Does the `getpwnam` function in Perl (5) work on FreeBSD ??

**Comment by pprocacci** [comment]
% perl -e ' print getpwnam("pprocacci"); '
pprocacci*100110010My Name/home/pprocacci/bin/tcsh0pprocacci@nas:~/git-repos/perl6-paws %

That's affirmative.

**Comment by lizmat** [comment]
Aha, looks like the `passwd` struct is different on FreeBSD.

Could you tell me what `perl6 -e 'say $*KERNEL.name'` says?

**Comment by pprocacci** [comment]
% perl6 -e 'say $*KERNEL.name'
freebsd

.... and in case you need it:

struct passwd {
        char    *pw_name;               /* user name */
        char    *pw_passwd;             /* encrypted password */
        uid_t   pw_uid;                 /* user uid */
        gid_t   pw_gid;                 /* user gid */
        time_t  pw_change;              /* password change time */
        char    *pw_class;              /* user access class */
        char    *pw_gecos;              /* Honeywell login info */
        char    *pw_dir;                /* home directory */
        char    *pw_shell;              /* default shell */
        time_t  pw_expire;              /* account expiration */
        int     pw_fields;              /* internal: fields filled in */
};

**Comment by lizmat** [comment]
Thanks, found it already.  Turns out, it's the same as MacOS, so I guess it goes for all BSD's.  A new release is on its way to CPAN now, expect it to be upgradable with zef within the next 2 hours or so.

Please let me know if this fixed it.  I have no way of testing this of FreeBSD myself.

**Comment by pprocacci** [comment]
Doesn't look like it woked.

% git clone https://github.com/lizmat/P5getpwnam.git
Cloning into 'P5getpwnam'...
remote: Enumerating objects: 7, done.
remote: Counting objects: 100% (7/7), done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 122 (delta 1), reused 2 (delta 0), pack-reused 115
Receiving objects: 100% (122/122), 23.63 KiB | 1.03 MiB/s, done.
Resolving deltas: 100% (58/58), done.
pprocacci@nas:~ % cd P5getpwnam/
pprocacci@nas:~/P5getpwnam % zef install .
===> Testing: P5getpwnam:ver<0.0.7>:auth<cpan:ELIZABETH>
\# Failed test 'did we see ourselves'
\# at t/getpwnam.t line 34
\# Failed test 'did we get the same number of entries the 2nd time'
\# at t/getpwnam.t line 38
\# expected: '0'
\#      got: '-27'
\# Looks like you failed 2 tests of 20
===> Testing [FAIL]: P5getpwnam:ver<0.0.7>:auth<cpan:ELIZABETH>
Aborting due to test failure: P5getpwnam:ver<0.0.7>:auth<cpan:ELIZABETH> (use --force-test to override)

**Comment by pprocacci** [comment]
The problem is here in the test file:

while getpwent() -> @result {

getpwent isn't returning my username.

test.pl6
--------------------
<.... snip .... >
$userid.say;
$username.say;
while getpwent() -> @result {
    say @result;
    $seen_me = True if @result[0] eq $username && @result[2] == $userid;
    ++$seen;
}
say $seen_me;


% ./test.pl6
1001
pprocacci
(git_daemon * 964 964 0  git daemon /nonexistent /usr/sbin/nologin 0)
(_tss * 601 601 0  TCG Software Stack user /var/empty /usr/sbin/nologin 0)
(messagebus * 556 556 0  D-BUS Daemon User /nonexistent /usr/sbin/nologin 0)
(avahi * 558 558 0  Avahi Daemon User /nonexistent /usr/sbin/nologin 0)
(git * 211 211 0  User & /GitRepositories /bin/sh 0)
(polkitd * 565 565 0  Polkit Daemon User /var/empty /usr/sbin/nologin 0)
(colord * 970 970 0  colord color management daemon /nonexistent /usr/sbin/nologin 0)
(cups * 193 193 0  Cups Owner /nonexistent /usr/sbin/nologin 0)
(Any)





However, if I just do the following without the tests:

while getpwent() -> @data {
    @data.say;
}

Then I do see my username.  

(And sorry about the formatting.  I don't know anything about github formatting.)

**Comment by lizmat** [comment]
wrt github formatting: either put code between backticks like `this`, or put 4 spaces before each line of code.

**Comment by pprocacci** [comment]
I think I know the problem .....

Probably need to `endpwent(void);`  somewhere before entering that loop.  Prior calls to these family of functions are probably keeping a fd somewhere and just using it.

A endpwent followed by your loop should resolve the issue I would think.

(And thanks for the formatting pointer).

**Comment by lizmat** [comment]
So, does this diff fix it (in t/getpwnam.t):

    +endpwent;   # seems FreeBSD needs this
    @result = getpwent;

**Comment by pprocacci** [comment]
No, that doesn't fix it.  The problem though is most certainly with that while loop in the test.
I'm not getting all records from the password database.

`hast:*:845:845::0:0:HAST unprivileged user:/var/empty:/usr/sbin/nologin
nobody:*:65534:65534::0:0:Unprivileged user:/nonexistent:/usr/sbin/nologin
pprocacci::1001:1001::0:0:Paul A. Procacci:/home/pprocacci:/bin/tcsh
git_daemon:*:964:964::0:0:git daemon:/nonexistent:/usr/sbin/nologin
_tss:*:601:601:daemon:0:0:TCG Software Stack user:/var/empty:/usr/sbin/nologin
messagebus:*:556:556::0:0:D-BUS Daemon User:/nonexistent:/usr/sbin/nologin
avahi:*:558:558::0:0:Avahi Daemon User:/nonexistent:/usr/sbin/nologin
git:*:211:211::0:0:User &:/GitRepositories:/bin/sh
polkitd:*:565:565::0:0:Polkit Daemon User:/var/empty:/usr/sbin/nologin
colord:*:970:970::0:0:colord color management daemon:/nonexistent:/usr/sbin/nologin
cups:*:193:193::0:0:Cups Owner:/nonexistent:/usr/sbin/nologin
`

This is my password database (partial database):

`@result = getpwnam($username);`
Is reading the above database and getting to pprocacci ... what we requested.

`@result = getpwent;`
Is reading the next line and returning git_daemon.

`while getpwent() -> @result {`
Is returning everything AFTER the git_daemon only.

I thought endpwent would fix it, but it isn't.

Edit: from my manpage ....   `The endpwent() function closes any open files.`

It seems I'm on the right track, but I don't know how to test this in a perl6ish environment.  I'm sure if I was using the language I'm most familiar with (C) this would work as I expect.

**Comment by lizmat** [comment]
Well, if you could verify that the test file would work in C, that would be a step forward  :-)

I don't have access to any FreeBSD boxes, so I can't really test easily.

**Comment by pprocacci** [comment]
I already did....and it doesn't.  ;)
I'll play around with this later from home (leaving work now)

**Comment by lizmat** [comment]
ok, about to call it a day here (11pm) so will check on this tomorrow

**Comment by ghost** [comment]
Just got home.  I was just thinking about this on my ride, and I believe there is a similar (but different) problem that affects linux as well.

Have you ever tried installing this module as root (on linux)?  If my hunch is correct, it'll fail.

getpwent is designed to be an iterative function.

line 23:  `@result = getpwent;`

This would gobble up the first entry in the password database then the subsequent `while getpwent() -> @result {` would miss whatever record was shifted off.

The following `diff` allows the module to install for me on FreeBSD and takes care of the shifting off problem that I just mentioned.

% diff -ur t.orig t
diff -ur t.orig/getpwnam.t t/getpwnam.t
--- t.orig/getpwnam.t   2019-12-17 18:04:31.054307000 -0500
+++ t/getpwnam.t        2019-12-17 18:05:49.915925000 -0500
@@ -25,7 +25,9 @@
 @result = getpwent;
 ok @result, 'did we get anything from getpwent';

-my int $seen = 1;
+setpwent;
+
+my int $seen = 0;
 my $seen_me;
 while getpwent() -> @result {
     $seen_me = True if @result[0] eq $username && @result[2] == $userid;

**Comment by lizmat** [comment]
0.08 on its way to CPAN.  Thanks!
